# 模型参数组
model_parameters:
  # 原始Onnx浮点模型文件
  onnx_model: 'LightTrack_sim.onnx'
  # 转换的目标AI芯片架构
  march: 'bernoulli2'
  # 模型转换输出的用于上板执行的模型文件的名称前缀
  output_model_file_prefix: 'LightTrack'
  # 模型转换输出的结果的存放目录
  working_dir: './model/'
  # 指定转换后混合异构模型是否保留输出各层的中间结果的能力
  layer_out_dump: False

# 输入信息参数组
input_parameters:
  # 原始浮点模型的输入节点名称
  input_name: "input1; input2"
  # 原始浮点模型的输入数据格式（数量/顺序与input_name一致）
  input_type_train: 'rgb; rgb'
  # 原始浮点模型的输入数据排布（数量/顺序与input_name一致）
  input_layout_train: 'NCHW; NCHW'
  # 原始浮点模型的输入数据尺寸
  input_shape: '1x3x128x128; 1x3x256x256'
  # 网络实际执行时，输入给网络的batch_size, 默认值为1
  #input_batch: 1; 1
  # 在模型中添加的输入数据预处理方法
  norm_type: 'data_mean_and_scale; data_mean_and_scale'
  # 预处理方法的图像减去的均值, 如果是通道均值，value之间必须用空格分隔
  mean_value: '123.675 116.28 103.53; 123.675 116.28 103.53'
  # 预处理方法的图像缩放比例，如果是通道缩放比例，value之间必须用空格分隔
  scale_value: '0.01712 0.01751 0.01743; 0.01712 0.01751 0.01743'
  # 转换后混合异构模型需要适配的输入数据格式（数量/顺序与input_name一致）
  input_type_rt: 'bgr; bgr'
  # 转换后混合异构模型需要适配的输入数据排布（数量/顺序与input_name一致），若input_type_rt配置为nv12，则此处参数不需要配置
  input_layout_rt: 'NHWC; NHWC'

# 校准参数组
calibration_parameters:
  # 模型校准使用的标定样本的存放目录
  cal_data_dir: './calibration/template/; ./calibration/search/'
  # 开启图片校准样本自动处理（skimage read; resize到输入节点尺寸）
  preprocess_on: False
  # 校准使用的算法类型
  calibration_type: 'default'
  # max 校准方式的参数
  #max_percentile: 1.0

# 编译参数组
compiler_parameters:
  # 编译策略选择
  compile_mode: 'latency'
  # 是否打开编译的debug信息
  debug: False
  # 模型运行核心数
  core_num: 2
  # 模型编译的优化等级选择
  optimize_level: 'O3'
